# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'RNCalendarKit' do
	# Uncomment the next line if you're using Swift or would like to use dynamic frameworks
	use_frameworks!

	# Pods for RNCalendarKit

	# pod 'CalendarKit'
	# pod 'CalendarKit', :path => '../../../_research/CalendarKit'
	pod 'CalendarKit', :git => 'https://github.com/Sionarch/CalendarKit.git'

  # pre_install do |installer|
  #   # workaround for https://github.com/CocoaPods/CocoaPods/issues/3289
  #   Pod::Installer::Xcode::TargetValidator.send(:define_method, :verify_no_static_framework_transitive_dependencies) {}
  # end

	post_install do |installer|
		installer.pods_project.targets.each do |target|
		target.build_configurations.each do |config|
			# config.build_settings['ENABLE_BITCODE'] = 'NO'
			config.build_settings['SWIFT_VERSION'] = '4.2'
		end
		# target.headers_build_phase.files.each do |file|
		# 	file.settings = { 'ATTRIBUTES' => ['Public'] }
		# end
		end
	end

  end
